language: node_js
node_js:
  - 11

jobs:
  include:
    - stage: lint
      before_install:
        - cd backend
      script:
        - eslint .
    - stage: test
      services:
        - mysql
      before_install:
        - cd backend/testing
        - mysql -u root --password="" < createdb.sql
        - pyenv install -y 3.7
        - pip install -y tavern
        - pip install -y tavern[pytest]
      script:
        - cd ..
        - npm start &
        - sleep 5
        - cd testing
        - py.test test_minimal.tavern.yaml  -v
