language: node_js
node_js:
  - 11

jobs:
  include:
    - stage: lint
      before_install:
        - cd backend
      script:
        - eslint .
    - stage: test
      services:
        - mysql
      before_install:
        - cd backend/testing
        - mysql -u root --password="" < createdb.sql
        - pyenv global 3.7
        - pip3 install tavern --user
        - pip3 install tavern[pytest] --user
      script:
        - cd ..
        - npm install
        - CI=1 npm start &
        - sleep 13
        - cd testing
        - PYTHONPATH=$PYTHONPATH:`pwd`/ py.test test_minimal.tavern.yaml -v
